name: field
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3
  - python=3.10
  - pip:
      - aiohttp==3.9.3
      - azure-core==1.29.7
      - azure-data-tables==12.5.0
      - azure-storage-blob==12.19.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - pandas==2.2.0
      - pyarrow==15.0.0
      - pyyaml==6.0.1
      - tqdm==4.64.1
      - matplotlib==3.8.4
      - ExifRead==3.0.0
      - seaborn==0.13.2