# Hydra defaults and settings. Ignore these (don't change)
defaults:
  # - override hydra/job_logging: custom # custom logging 
  - paths: default
  - _self_

hydra:
  run:
    dir: ${logs.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
    # - wir_table_generator
    # - wir_blob_data_generator
    # - process_blob_analysis
    # - process_tables_analysis
    # - append_datetime
    # - create_batches
    # - report
    - image_inspection
    # - plot_by_season

general:
  task: # Leave empty as placeholder
  workdir: ${hydra:runtime.cwd}  # where the code is executed

pipeline_keys: ${general.workdir}/keys/authorized_keys.yaml

inspection:
  num_past_days_to_inspect: 180
  num_images_to_inspect: 5

logs:
  logdir: ${general.workdir}/logging

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}

state_list:
  - AL
  - DV
  - GA
  - IL
  - KS
  - MD
  - MS
  - NC
  - NC01
  - TX
  - TX01
  - TX02
  - VA
  - NY
  - KS