# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - paths: default
  - _self_

hydra:
  run:
    dir: ${logs.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

pipeline:
    - wir_table_generator
    - wir_blob_data_generator
    - merge_samples
    - append_datetime_db
    - report_db
    - plot_by_season_db
    # - image_inspection
    # - create_batches_db

general:
  task: # Leave empty as placeholder
  workdir: ${hydra:runtime.cwd}  # where the code is executed

pipeline_keys: ${general.workdir}/keys/authorized_keys.yaml

inspection:
  num_past_days_to_inspect: 7
  num_past_days_for_report: 7
  num_images_to_inspect: 50

logs:
  logdir: ${general.workdir}/logging

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H_%M_%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}

state_list:
  - AL
  - DV
  - GA
  - IL
  - KS
  - MD
  - MS
  - NC
  - NC01
  - TX
  - TX01
  - TX02
  - VA
  - NY
  - OH

sources:
  - name: weedsimagerepo
    type: azure_blob
    key_ref: weedsimagerepo
    entity: image
  - name: wirimagerefs
    type: azure_table
    key_ref: wirimagerefs
    entity: image_ref
  - name: wirmastermeta
    type: azure_table
    key_ref: wirmastermeta
    entity: sample_attributes
    master_ref_key: RowKey
  - name: wircovercropsmeta
    type: azure_table
    key_ref: wircovercropsmeta
    entity: sample_attributes
  - name: wircropsmeta
    type: azure_table
    key_ref: wircropsmeta
    entity: sample_attributes
  - name: wirweedsmeta
    type: azure_table
    key_ref: wirweedsmeta
    entity: sample_attributes
  - name: wirsoilsmeta
    type: azure_table
    key_ref: wirsoilsmeta
    entity: sample_attributes
  - name: wirlogs
    type: azure_table
    key_ref: wirlogs
    entity: none

coalesce_fields:
  UsState: [{source: wirmastermeta, field: UsState}]
  PlantType: [{source: wirmastermeta, field: PlantType}]
  CloudCover: [{source: wirmastermeta, field: CloudCover}]
  GroundResidue: [{source: wirmastermeta, field: GroundResidue}]
  GroundCover: [{source: wirmastermeta, field: GroundCover}]
  Username: [{source: wirmastermeta, field: Username}]
  CoverCropFamily: [{source: wircovercropsmeta, field: CoverCropFamily}]
  GrowthStage: [{source: wircropsmeta, field: GrowthStage}]
  CottonVariety: [{source: wircropsmeta, field: CottonVariety}]
  CropOrFallow: [{source: wirweedsmeta, field: CropOrFallow}]
  CropTypeSecondary: [{source: wirweedsmeta, field: CropType}]
  Species:
    - {source: wirweedsmeta, field: WeedType}
    - {source: wircovercropsmeta, field: CoverCropSpecies}
    - {source: wircropsmeta, field: CropName}
  Height:
    - {source: wircropsmeta, field: Height}
    - {source: wirweedsmeta, field: Height}
  SizeClass:
    - {source: wircropsmeta, field: SizeClass}
    - {source: wirweedsmeta, field: SizeClass}
  FlowerFruitOrSeeds:
    - {source: wircovercropsmeta, field: FlowerFruitOrSeeds}
    - {source: wirweedsmeta, field: FlowerFruitOrSeeds}

