# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - override hydra/job_logging: custom # custom logging 
  - _self_

hydra:
  run:
    dir: ${logs.logdir}/${job.job_now}
  output_subdir: ${hydra.run.dir}/hydra

general:
  task: ???
  workdir: ${hydra:runtime.cwd}  # where the code is executed

pipeline_keys: ${general.workdir}/keys/authorized_keys.yaml

job:
  job_now_date: &nowdir ${now:%Y-%m-%d}
  job_now_time: ${now:%H:%M:%S}
  job_now: ${job.job_now_date}/${job.job_now_time} 
  jobdir: ${data.datadir}/${job.job_now}

logs:
  logdir: ${general.workdir}/logging
  processed: ${logs.logdir}/processed.txt

data:
  datadir: ${general.workdir}/data
  tablesdir: ${data.datadir}/tables/${job.job_now_date}
  blobsdir: ${data.datadir}/blobs/${job.job_now_date}

