import dataclasses


@dataclasses
class FieldMetadata:
    ApertureValue: None
    BodySerialNumber: None
    BrightnessValue: None
    Container: None
    CloudCover: None
    ColorSpace: None
    ComponentsConfiguration: None
    CompressedBitsPerPixel: None
    Contrast: None
    CottonVariety: None
    CoverCropFamily: None
    Creation_time_utc: None
    CropOrFallow: None
    CropTypeSecondary: None
    DateTime: None
    DateTimeOriginal: None
    DigitalZoomRatio: None
    ExifOffset: None
    ExifVersion: None
    ExposureBiasValue: None
    ExposureMode: None
    ExposureProgram: None
    ExposureTime: None
    Extension: None
    FNumber: None
    Flash: None
    FlashPixVersion: None
    FlowerFruitOrSeeds_01: None
    FlowerFruitOrSeeds_02: None
    FocalLength: None
    FocalLengthIn35mmFilm: None
    GroundCover: None
    GroundResidue: None
    GrowthStage: None
    Height: None
    ISOSpeedRatings: None
    ImageIndex: None
    ImageLength: None
    ImageURL: None
    ImageUniqueID: None
    ImageWidth: None
    LensModel: None
    LensSpecification: None
    LightSource: None
    Make: None
    MasterRefID: None
    MaxApertureValue: None
    Memory_mb: None
    MeteringMode: None
    Model: None
    Name: None
    Orientation: None
    PlantType: None
    PrintIM: None
    Saturation: None
    SensingMethod: None
    SensitivityType: None
    Sharpness: None
    ShutterSpeedValue: None
    SizeClass: None
    Software: None
    Species: None
    SubSecTime: None
    SubSecTimeDigitized: None
    SubSecTimeOriginal: None
    UsState: None
    Username: None
    WhiteBalance: None
    YCbCrPositioning: None
